In [50]:
import pandas as pd

In [51]:
resid_population = pd.read_csv('지역별(행정동) 성별 연령별 주민등록 인구수_20231031.csv', encoding='cp949')
resid_population.head()

,행정기관코드,기준연월,시도명,시군구명,읍면동명,계,남자,여자,만0세남자,만1세남자,...,만101세여자,만102세여자,만103세여자,만104세여자,만105세여자,만106세여자,만107세여자,만108세여자,만109세여자,만110세이상여자
0,1111051500,2023-10-31,서울특별시,종로구,청운효자동,11345,5181,6164,21,21,...,1,1,0,0,0,0,0,0,0,0
1,1111053000,2023-10-31,서울특별시,종로구,사직동,9016,4005,5011,12,15,...,0,0,0,0,0,0,0,0,0,0
2,1111054000,2023-10-31,서울특별시,종로구,삼청동,2246,1073,1173,3,2,...,1,0,0,0,0,0,0,0,0,0
3,1111055000,2023-10-31,서울특별시,종로구,부암동,9125,4319,4806,9,10,...,2,1,1,0,0,0,0,0,0,0
4,1111056000,2023-10-31,서울특별시,종로구,평창동,17415,8107,9308,33,43,...,4,0,0,1,0,0,0,0,1,0

In [52]:
def resid_population_group(data, code):
  data = resid_population[resid_population['행정기관코드'] == code]

  age_under_10 = data.iloc[0,8:28].sum() + data.iloc[0,119:139].sum()
  age_20_30 = data.iloc[0,28:48].sum() + data.iloc[0,139:159].sum()
  age_40_50 = data.iloc[0,48:68].sum() + data.iloc[0,159:179].sum()
  age_above_60 = data.iloc[0,68:119].sum() + data.iloc[0,179:230].sum()

  total_list = [age_under_10, age_20_30, age_40_50, age_above_60]

  return total_list

In [53]:
codes = [4817056500, 5113051500, 4122060000, 4513060500, 4111574000, 4313051500, 4713055000,
         4413151000, 1141055500, 4719025000, 4511171100, 2771026500, 4613057000, 5111054500,
         4728057000, 4717058500, 4471025000, 5177025000, 2723063000, 4817056500, 1123054500,
         5123051000, 5177025600, 4572025000, 4571025000, 4825051000, 3114052000, 5011053000,
         4521051000, 2711057500, 4127155000, 5011051000, 4888025000, 4715053600, 4127158000,
         4514052000, 2611057000, 2623052000, 2811053000, 3011051500]

In [56]:
group_list = []

for code in codes:
  group_list.append(resid_population_group(resid_population, code))

In [57]:
final_data = pd.DataFrame(group_list, columns = ['age_under_10', 'age_20_30', 'age_40_50', 'age_above_60'])
final_data

    age_under_10  age_20_30  age_40_50  age_above_60
0            837       1856       2852          5094
1            106        286        703          1289
2           1481       4371       4082          3379
3            424        846       1209          1662
4            588       2505       2840          3610
5            230        430        681          1160
6           1111       3324       3748          5440
7            395       1010       1471          2237
8           2284       4702       5015          3450
9           1714       2179       4417          5733
10          1948       3006       3896          4204
11          3872       6762       6744          5255
12           319        561       1092          1931
13           955       1530       1549          1400
14           664        893       1545          2370
15          1300       1357       2580          3219
16          3727       3896       7335          7844
17          1367       1593       3231          3775
18           592       3843       1997          2493
19           837       1856       2852          5094
20          2001       7409       6134          7669
21           632       1142       1989          3281
22           563        655       1480          1690
23          1334       1543       2815          4035
24          3083       5368       5548          5787
25          1012       2146       2947          2961
26          5015       5560       9040          5118
27          1150       1950       2369          2183
28          1568       2171       3212          3859
29           468       1846       1257          1515
30          3520       6589       8968          6026
31           173        376        706           945
32          7521       7943      12562         11863
33           517       1293       1936          3395
34          4860      10796      12696          8349
35           175        631        780          1466
36            65        145        271           439
37          1166       4961       3107          2262
38           518        909       1518          1772
39           178        521       1062          2102

In [59]:
final_data.to_csv('주민등록인구.csv', index=False)